const products = [
    {
      _id: '1',
      name: 'Airpods Wireless Bluetooth Headphones',
      image: '/Images/Img10.jpg',
      Date: 'Sat, Mar 19',
      Time: '2:00 PM',
      Address: 'Magnuson Park Hangar 30 • Seattle,WA',
      Followers: '570',
    },
    {
        _id: '2',
        name: 'Airpods Wireless Bluetooth Headphones',
        image: '/Images/Img11.jpg',
        Date: 'Sat, Mar 19',
        Time: '2:00 PM',
        Address: 'Magnuson Park Hangar 30 • Seattle,WA',
        Followers: '570',
    },
    {
        _id: '3',
        name: 'Airpods Wireless Bluetooth Headphones',
        image: '/Images/Img3.jpg',
        Date: 'Sat, Mar 19',
        Time: '2:00 PM',
        Address: 'Magnuson Park Hangar 30 • Seattle,WA',
        Followers: '570',
    },
    {
        _id: '4',
        name: 'Airpods Wireless Bluetooth Headphones',
        image: '/Images/Img4.jpg',
        Date: 'Sat, Mar 19',
        Time: '2:00 PM',
        Address: 'Magnuson Park Hangar 30 • Seattle,WA',
        Followers: '570',
    },
    {
        _id: '5',
        name: 'Airpods Wireless Bluetooth Headphones',
        image: '/Images/Img5.jpg',
        Date: 'Sat, Mar 19',
        Time: '2:00 PM',
        Address: 'Magnuson Park Hangar 30 • Seattle,WA',
        Followers: '570',
    },
    {
        _id: '6',
        name: 'Airpods Wireless Bluetooth Headphones',
        image: '/Images/Img6.jpg',
        Date: 'Sat, Mar 19',
        Time: '2:00 PM',
        Address: 'Magnuson Park Hangar 30 • Seattle,WA',
        Followers: '570',
    },
    {
        _id: '6',
        name: 'Airpods Wireless Bluetooth Headphones',
        image: '/Images/Img7.jpg',
        Date: 'Sat, Mar 19',
        Time: '2:00 PM',
        Address: 'Magnuson Park Hangar 30 • Seattle,WA',
        Followers: '570',
    },
    {
        _id: '6',
        name: 'Airpods Wireless Bluetooth Headphones',
        image: '/Images/Img9.jpg',
        Date: 'Sat, Mar 19',
        Time: '2:00 PM',
        Address: 'Magnuson Park Hangar 30 • Seattle,WA',
        Followers: '570',
    },
  ]
  
  export default products